{
	"version": 1565940921,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/menu_1-sheet0.png",
		"images/menu_2-sheet0.png",
		"images/menu_3-sheet0.png",
		"images/menu_4-sheet0.png",
		"images/menu_5-sheet0.png",
		"images/bg_kuning-sheet0.png",
		"images/header-sheet0.png",
		"images/sprite-sheet0.png",
		"images/cmd_back-sheet0.png",
		"images/img_orang-sheet0.png",
		"images/img_orang-sheet1.png",
		"images/img_orang-sheet2.png",
		"images/img_orang-sheet3.png",
		"images/sprite2-sheet0.png",
		"images/img_awal-sheet0.png",
		"images/img_detail-sheet0.png",
		"images/img_detail-sheet1.png",
		"images/img_detail-sheet2.png",
		"images/img_detail-sheet3.png",
		"images/img_detail-sheet4.png",
		"images/img_detail-sheet5.png",
		"images/menu_6-sheet0.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"dalam rumah.mov",
		"luar rumah.mov",
		"di mobil.mov",
		"gunung.mov",
		"layout website.png",
		"pantai 2.mov",
		"sekolah dalam kelas.mov"
	]
}